(library (utility tool)
	 (export handle-tree)
	 (import (rnrs))

	 (define (handle-tree tree exp env)
	   (if (null? tree)
	       (error 'handle-tree "error")
	       (let* ((head (car tree))
		      (predicator (car head))
		      (decision (cadr head)))
		 (if (predicator exp)
		     (if (not (list? decision))
			 (decision exp env)
			 (handle-tree decision exp env))
		     (handle-tree (cdr tree) exp env)))))
)

